### PR TITLE
NMS-14637: Remove footer content from opennms/docs.opennms.com

### PR DESCRIPTION
**Pull request by Bonrob2**
NMS-14637: Remove footer content from opennms/docs.opennms.com - removed footer content, as it would overwrite footer content that specifies the copyright date and had link to legal notice, as per reviewer feedback on NMS-13911

JIRA: https://issues.opennms.org/browse/NMS-13911

### CODE REVIEW

**Comment by Bonrob2** [comment]
@indigo423 or @RangerRick  could you review this PR?

**Review by indigo423 — COMMENTED** [review]
The docs repository uses the Antora OpenNMS UI version 2.0.6. To make usage of your new updated footer I've released Antora OpenNMS UI 3.0.1, which has your updated footer. If you want to see your changes from the UI here in this repository, you need to update the UI bundle to use version 3.0.1 here in this repo. This [line](https://github.com/OpenNMS/docs.opennms.com/blob/be78260a538f5654366ec02c7b4e8809c0de34a6/antora-playbook.yml#L75) here is the place where you can tell Antora which UI version it should use for the build.


https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.0.1/ui-bundle.zip

**Review by mmahacek — APPROVED** [review]

**Comment by mmahacek** [comment]
> The docs repository uses the Antora OpenNMS UI version 2.0.6. To make usage of your new updated footer I've released Antora OpenNMS UI 3.0.1, which has your updated footer. If you want to see your changes from the UI here in this repository, you need to update the UI bundle to use version 3.0.1 here in this repo. This [line](https://github.com/OpenNMS/docs.opennms.com/blob/be78260a538f5654366ec02c7b4e8809c0de34a6/antora-playbook.yml#L75) here is the place where you can tell Antora which UI version it should use for the build.
> 
> https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.0.1/ui-bundle.zip

Do we need to update this line in all the other projects, so they render with the new UI bundle? (which I'm assuming changes after https://github.com/opennms-forge/antora-ui-opennms/pull/26)

**Comment by Bonrob2** [comment]
> Do we need to update this line in all the other projects, so they render with the new UI bundle? (which I'm assuming changes after [opennms-forge/antora-ui-opennms#26](https://github.com/opennms-forge/antora-ui-opennms/pull/26))

Yes, I think so, but will let @indigo423 confirm.

Have created NMS-14666 to update the other doc repos.

**Pull request merged**
