### PR TITLE
NMS-15155: Add Google Analytics and Search Console tags 

### PR DESCRIPTION
**Pull request by Bonrob2**
Added google_analytics key to playbook file.

### CODE REVIEW

**Comment by Bonrob2** [comment]
@mmahacek, could you review this and let me know if you see anything I've overlooked? Thanks!

**Review by emarsh1995 — COMMENTED** [review]
LGTM, I think! Not too familiar with Google Analytics, so I'll leave the actual approvals to others. :)

**Review by mmahacek — COMMENTED** [review]
According to the docs, this is enough when using the default Antora UI.  I'm not sure if our customizations still count as using the default or not.  If not, we'd also need to specify the tag manager code in the page headers.  Would need an updated UI bundle ZIP to build product docs against to test.

**Comment by Bonrob2** [comment]
> According to the docs, this is enough when using the default Antora UI. I'm not sure if our customizations still count as using the default or not. If not, we'd also need to specify the tag manager code in the page headers. Would need an updated UI bundle ZIP to build product docs against to test.
I'm not sure if our customizations count as the default UI either. Will look into what you suggest to specify the tag manager code. Thanks!

UPDATE @mmahacek , looks like our UI bundle already has the tag manager code in the headers. I just need to add the ID, I believe.
Screenshot 2023-04-04 at 11 47 50 AM

**Review by mmahacek — APPROVED** [review]
Looks like the necessary GA4 tag is part of the ui-bundle, so this should be good.

**Pull request merged**
